# Minikube Configuration
# This file contains settings for minikube cluster setup

# Cluster Configuration
CLUSTER_NAME="redis-dev"
DRIVER="docker"              # Options: docker, virtualbox, kvm2, hyperkit
CPUS="2"
MEMORY="4096"               # MB
DISK_SIZE="20g"

# Kubernetes Configuration
KUBERNETES_VERSION="v1.28.0"

# Addons to enable
ADDONS=(
    "dashboard"
    "ingress"
    "metrics-server"
    "storage-provisioner"
)

# Namespace for Redis deployment
REDIS_NAMESPACE="redis-dev"

# Redis Configuration
REDIS_INSTANCE_NAME="redis-server"
REDIS_PORT="6379"
LOCAL_PORT="6379"
