services:
  postgres:
    image: postgres:15-alpine
    container_name: redisgate-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-redisgate_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-redisgate_dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-redisgate_dev}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-redisgate_dev}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redisgate-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redisgate_redis_password}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-redisgate_redis_password}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis Insight for debugging/monitoring Redis
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redisgate-redis-insight
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  redis_insight_data:
    driver: local

networks:
  default:
    name: redisgate-dev-network