services:
  postgres:
    image: postgres:15-alpine
    container_name: redisgate-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-redisgate_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-redisgate_dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-redisgate_dev}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-redisgate_dev}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: redisgate-dev-network