apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: redis-dev
  labels:
    app: redis-server
spec:
  type: ClusterIP
  selector:
    app: redis-server
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP

---
# Optional: NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: redis-server-nodeport
  namespace: redis-dev
  labels:
    app: redis-server
spec:
  type: NodePort
  selector:
    app: redis-server
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30379
    protocol: TCP
