apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apikeys.redis.kubegateway.io
spec:
  group: redis.kubegateway.io
  names:
    kind: ApiKey
    listKind: ApiKeyList
    plural: apikeys
    singular: apikey
    shortNames:
      - rak
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: User
          type: string
          jsonPath: .spec.userId
        - name: ExpiresAt
          type: date
          jsonPath: .spec.expiresAt
      schema:
        openAPIV3Schema:
          type: object
          description: API key resource for Redis HTTP gateway access control
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - userId
                - permissions
              properties:
                userId:
                  type: string
                  minLength: 1
                permissions:
                  type: array
                  minItems: 1
                  items:
                    type: string
                    enum:
                      - read
                      - write
                      - admin
                instanceAccess:
                  type: array
                  items:
                    type: string
                    pattern: '^[a-z0-9-]+$'
                  description: List of RedisHttpInstance names this key can access
                expiresAt:
                  type: string
                  format: date-time
                  description: ISO-8601 time when key expires
            status:
              type: object
              properties:
                keyHash:
                  type: string
                  description: Hash of the API key value (never store raw key)
                createdAt:
                  type: string
                  format: date-time
                lastUsed:
                  type: string
                  format: date-time
# commit: feat(crd): add ApiKey CRD (v1alpha1)
